/* === ACTIONS === */

//action types
/*Launches */
export const API_LAUNCHES_REQUEST = "API_LAUNCHES_REQUEST";
export const API_LAUNCHES_SUCCESS = "API_LAUNCHES_SUCCESS";
export const API_LAUNCHES_FAILURE = "API_LAUNCHES_FAILURE";

/*Rockets */
export const API_ROCKETS_REQUEST = "API_ROCKETS_REQUEST";
export const API_ROCKETS_SUCCESS = "API_ROCKETS_SUCCESS";
export const API_ROCKETS_FAILURE = "API_ROCKETS_FAILURE";
